name: Simple Development CI

on:
  push:
    branches: [ master ]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build check
      run: npm run build
      continue-on-error: true

    - name: Simple test check
      run: npm test -- --passWithNoTests --silent
      continue-on-error: true